services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=jefred
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=jefred
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=admin123
    ports:
      - 8081:80
    volumes:
      - ./phpmyadmin_data:/sessions
